Jupyter Extension Version: 2021.11.1001550889.
Python Extension not installed.
Info 09:09:08: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 09:09:08: ZMQ install verified.
Info 09:09:09: Find preferred kernel for ~/DOCKER_eval/test00.ipynb with metadata {"language_info":{"name":"plaintext"},"orig_nbformat":4} & preferred interpreter 
Info 09:10:00: Notebook Closed ~/DOCKER_eval/test00.ipynb
Info 09:10:00: Find preferred kernel for ~/DOCKER_eval/tests.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"plaintext"}} & preferred interpreter 
Info 09:10:18: Setting setActiveController for ~/DOCKER_eval/tests.ipynb
Info 09:10:18: KernelProvider switched kernel to id = .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
Info 09:10:21: Execute Cells request 0
Info 09:10:21: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:10:21: Starting Notebook in kernel.ts id = .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
Info 09:10:21: Creating raw notebook for ~/DOCKER_eval/tests.ipynb
Info 09:10:21: Getting preferred kernel for ~/DOCKER_eval/tests.ipynb
Info 09:10:21: Computing working directory ~/DOCKER_eval/tests.ipynb
Info 09:10:21: Starting raw kernel Python 3.8.10 64-bit
Info 09:10:21: installMissingDependencies /bin/python3
Info 09:10:21: IPykernel found previously in this enviornment /bin/python3
Info 09:10:21: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 09:10:21: Launching Raw Kernel & not daemon Python 3.8.10 64-bit # python
Info 09:11:09: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 09:11:09: No custom variables for Kernel as interpreter is not conda, but is Global
Info 09:11:09: Process Execution: > python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2e272dc2-691d-4e07-8e9a-a6c39282af77" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-125789qYMhugut5KGL.json
> python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"2e272dc2-691d-4e07-8e9a-a6c39282af77" --shell=9002 --transport="tcp" --iopub=9004 --f=/tmp/tmp-125789qYMhugut5KGL.json
Info 09:11:09: Process Execution: cwd: ~/DOCKER_eval
cwd: ~/DOCKER_eval
Error 09:11:09: Kernel died [Error: spawn python ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
	at onErrorNT (internal/child_process.js:465:16)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn python',
  path: 'python',
  spawnargs: [
    '-m',
    'ipykernel_launcher',
    '--ip=127.0.0.1',
    '--stdin=9003',
    '--control=9001',
    '--hb=9000',
    '--Session.signature_scheme="hmac-sha256"',
    '--Session.key=b"2e272dc2-691d-4e07-8e9a-a6c39282af77"',
    '--shell=9002',
    '--transport="tcp"',
    '--iopub=9004',
    '--f=/tmp/tmp-125789qYMhugut5KGL.json'
  ]
} 
Info 09:11:09: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
Info 09:11:43: Interrupt requested & sent for file:///home/ubuntu/DOCKER_eval/tests.ipynb in notebookEditor.
Info 09:11:43: Interrupt requested file:///home/ubuntu/DOCKER_eval/tests.ipynb
Info 09:11:43: Dispose Kernel process
Error 09:11:43: Disposing kernel process due to an error [a [Error]: Canceled
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:16:52229
	at u.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at y.cancel (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:6253)
	at i.cancel (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:6794)
	at t.Kernel.interrupt (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:24:83578)
	at _.interruptKernel (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:358702)
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:356668
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:370452
	at r._executeContributedCommand (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:95:31080)
	at r._doExecuteCommand (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:95:29968)
	at r.executeCommand (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:95:29874)
	at Object.executeCommand (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:104:22022)
	at l.executeCommand (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:104:370799)
	at t.VSCodeNotebookController.handleInterrupt (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1427679)
	at s.$cancelCells (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:95:151579)
	at t._doInvokeHandler (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:99:13802)
	at t._invokeHandler (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:99:13486)
	at t._receiveRequest (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:99:12148)
	at t._receiveOneMessage (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:99:10826)
	at /home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:99:8922
	at u.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at r.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:74:18942)
	at /home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:114:34341
	at u.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at r.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:74:18942)
	at n._receiveMessage (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:74:23523)
	at /home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:74:21057
	at u.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at w.acceptChunk (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:74:15770)
	at /home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:74:14900
	at u.fire (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:66:1712)
	at s._processReadQueue (/home/ubuntu/.vscode-server/bin/fe719cd3e5825bf14e14182fddeb88ee8daf044f/out/vs/server/remoteExtensionHostProcess.js:114:21295)] {
  category: 'cancelled'
}
Error 09:11:43: 
Warn 09:11:43: User cancelled the kernel launch
Info 09:11:43: Starting of raw session cancelled by user
Error 09:11:43: failed to create INotebook in kernel, UI Disabled = false [a [Error]: Canceled
	at r.launchProcess (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:514281)
	at async /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:513527] {
  category: 'cancelled'
}
Warn 09:11:43: Cancelled by user [a [Error]: Canceled
	at r.launchProcess (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:514281)
	at async /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:513527] {
  category: 'cancelled'
}
Error 09:11:43: DataScience Error [a [Error]: Canceled
	at r.launchProcess (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:514281)
	at async /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:513527] {
  category: 'cancelled'
}
Error 09:11:43: failed to start INotebook in kernel, UI Disabled = false [a [Error]: Canceled
	at r.launchProcess (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:514281)
	at async /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:513527] {
  category: 'cancelled'
}
Info 09:11:43: Interrupt kernel execution
Info 09:11:43: Cancel pending cells
Info 09:11:43: No notebook to interrupt
Error 09:11:43: Failed to execute cells in CellExecutionQueue [a [Error]: Canceled
	at r.launchProcess (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:514281)
	at async /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:51:513527] {
  category: 'cancelled'
}
Info 09:11:43: Cancel pending cells
Info 09:11:43: Cell 0 executed with state Idle
Info 09:11:55: Execute Cells request 0
Info 09:11:55: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:11:55: Starting Notebook in kernel.ts id = .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
Info 09:11:55: Creating raw notebook for ~/DOCKER_eval/tests.ipynb
Info 09:11:55: Getting preferred kernel for ~/DOCKER_eval/tests.ipynb
Info 09:11:55: Computing working directory ~/DOCKER_eval/tests.ipynb
Info 09:11:55: Starting raw kernel Python 3.8.10 64-bit
Info 09:11:55: installMissingDependencies /bin/python3
Info 09:11:55: IPykernel found previously in this enviornment /bin/python3
Info 09:11:55: Kernel launching with ports 9008,9009,9010,9011,9012. Start port is 9000
Info 09:11:55: Launching kernel daemon for Python 3.8.10 64-bit # /bin/python3
Info 09:11:55: No custom variables for Kernel as interpreter is not conda, but is Global
Info 09:11:55: Creating daemon process for /bin/python3 with env variables count 0
Info 09:11:55: Process Execution: > /bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 09:11:55: Starting kernel from scratch
Warn 09:11:55: StdErr from Kernel Process /bin/python3: No module named ipykernel_launcher

Error 09:11:55: Kernel died [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
} /bin/python3: No module named ipykernel_launcher

Error 09:11:55: KernelProcess Exit Exit - 1, /bin/python3: No module named ipykernel_launcher
 [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
}
Error 09:11:55: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
}
Error 09:11:55: /bin/python3: No module named ipykernel_launcher

Info 09:11:55: Dispose Kernel process
Info 09:11:55: kill daemon
Error 09:11:55: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
Error 09:11:55: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
}
Error 09:11:55: failed to start INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
}
Error 09:11:55: Failed to execute cells in CellExecutionQueue [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
}
Info 09:11:55: Cancel pending cells
Info 09:11:55: Cell 0 executed with state Idle
Info 09:11:55: Process Execution: > /bin/python3 -c "import ipykernel"
> /bin/python3 -c "import ipykernel"
Info 09:11:55: installMissingDependencies /bin/python3
Info 09:11:55: Process Execution: > /bin/python3 -c "import ipykernel"
> /bin/python3 -c "import ipykernel"
Info 09:11:56: Process Execution: > /bin/python3 -c "import pip"
> /bin/python3 -c "import pip"
Info 09:12:01: Got result from python installer for ipykernel, result = 2
Info 09:12:22: Got result from python installer for ipykernel, result = 0
Info 09:12:22: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
Info 09:12:22: Process Execution: > /bin/python3 -c "import ipykernel"
> /bin/python3 -c "import ipykernel"
Error 09:12:22: DataScience Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /bin/python3: No module named ipykernel_launcher....
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/home/ubuntu/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/bin/python3: No module named ipykernel_launcher\n'
}
Info 09:12:24: Execute Cells request 0
Info 09:12:24: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:12:24: Starting Notebook in kernel.ts id = .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
Info 09:12:24: Creating raw notebook for ~/DOCKER_eval/tests.ipynb
Info 09:12:24: Getting preferred kernel for ~/DOCKER_eval/tests.ipynb
Info 09:12:24: Computing working directory ~/DOCKER_eval/tests.ipynb
Info 09:12:24: Starting raw kernel Python 3.8.10 64-bit
Info 09:12:24: installMissingDependencies /bin/python3
Info 09:12:24: IPykernel found previously in this enviornment /bin/python3
Info 09:12:24: Kernel launching with ports 9016,9017,9018,9019,9020. Start port is 9000
Info 09:12:24: Launching kernel daemon for Python 3.8.10 64-bit # /bin/python3
Info 09:12:24: No custom variables for Kernel as interpreter is not conda, but is Global
Info 09:12:24: Creating daemon process for /bin/python3 with env variables count 0
Info 09:12:24: Process Execution: > /bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 09:12:24: Starting kernel from scratch
Warn 09:12:25: StdErr from Kernel Process /home/ubuntu/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.

Warn 09:12:25: StdErr from Kernel Process   warn(

Warn 09:12:25: StdErr from Kernel Process /home/ubuntu/.local/lib/python3.8/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1704b3cf-919b-4574-b8dd-83378a7c7f59' instead of 'b"1704b3cf-919b-4574-b8dd-83378a7c7f59"'.

Warn 09:12:25: StdErr from Kernel Process   warn(

Info 09:12:25: Raw session started and connected
Started kernel Python 3.8.10 64-bit
Info 09:12:25: Finished connecting 80ad0bb0-ce16-4b01-89f3-15fcc8a4645e
Info 09:12:25: UpdateWorkingDirectoryAndPath in Kernel
Info 09:12:25: changeDirectoryIfPossible
Info 09:12:25: Executing (status idle) silently Code = import os\nimport sys\n%cd "/home/ubuntu/DOCKER_eval"\nif os.getcwd() not in sys.path:\nsys.path.ins
Info 09:12:25: Executing silently Code (completed) = import os\nimport sys\n%cd "/home/ubuntu/DOCKER_eval"\nif os.getcwd() not in sys.path:\nsys.path.ins
Info 09:12:25: Executing (status idle) silently Code = %config Completer.use_jedi = False
Info 09:12:26: Executing silently Code (completed) = %config Completer.use_jedi = False
Info 09:12:26: Initialize matplotlib for file:///home/ubuntu/DOCKER_eval/tests.ipynb
Info 09:12:26: Executing (status idle) silently Code = import matplotlib\n%matplotlib inline\n_VSCode_defaultMatplotlib_Params = dict(matplotlib.rcParams)\n%c
Info 09:12:26: Executing silently Code (completed) = import matplotlib\n%matplotlib inline\n_VSCode_defaultMatplotlib_Params = dict(matplotlib.rcParams)\n%c
Info 09:12:26: Executing (status idle) silently Code = matplotlib.style.use('dark_background')
Info 09:12:26: Executing silently Code (completed) = matplotlib.style.use('dark_background')
Info 09:12:26: Executing (status idle) silently Code = import sys\nprint(sys.executable)
Info 09:12:26: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 09:12:26: Waiting for idle on (kernel): b775fa3f-e0f8-494d-91a4-ec76ac36c8d7 -> idle
Info 09:12:26: Finished waiting for idle on (kernel): b775fa3f-e0f8-494d-91a4-ec76ac36c8d7 -> idle
Info 09:12:26: IPyWidgetScriptSource.initialize
Info 09:12:26: Cancel all remaining cells true || Error
Info 09:12:26: Cancel pending cells
Info 09:12:26: Cell 0 executed with state Error
Info 09:12:49: Execute Cells request 0
Info 09:12:49: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:12:49: Cell 0 executed with state Success
Info 09:21:59: Execute Cells request 0
Info 09:21:59: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:21:59: Cell 0 executed with state Success
Info 09:25:35: Execute Cells request 0
Info 09:25:35: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:25:36: Cell 0 executed with state Success
Info 09:25:57: Execute Cells request 0
Info 09:25:57: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:25:57: Cell 0 executed with state Success
Info 09:26:26: Execute Cells request 0
Info 09:26:26: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:26:26: Cell 0 executed with state Success
Info 09:26:35: Execute Cells request 0
Info 09:26:35: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:26:35: Cell 0 executed with state Success
Info 09:34:23: Execute Cells request 0
Info 09:34:23: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:34:23: Cancel all remaining cells true || Error
Info 09:34:23: Cancel pending cells
Info 09:34:23: Cell 0 executed with state Error
Info 09:36:32: Execute Cells request 0
Info 09:36:32: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:36:32: Cell 0 executed with state Success
Info 09:37:05: Execute Cells request 0
Info 09:37:05: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:37:05: Cell 0 executed with state Success
Info 09:37:24: Execute Cells request 0
Info 09:37:24: Execute Cell 0 ~/DOCKER_eval/tests.ipynb
Info 09:37:24: Cell 0 executed with state Success
Info 10:29:40: Shutting down notebooks for 80ad0bb0-ce16-4b01-89f3-15fcc8a4645e
Info 10:29:40: Disposing HostJupyterExecution 6941b51f-20c1-41a7-a788-74e69f3fd0fb
Info 10:29:40: Disposing super HostJupyterExecution 6941b51f-20c1-41a7-a788-74e69f3fd0fb
Info 10:29:40: Dispose kernel file:///home/ubuntu/DOCKER_eval/tests.ipynb
Info 10:29:40: Dispose Kernel process
Info 10:29:40: kill daemon
Info 10:29:40: Disposing HostJupyterExecution 6941b51f-20c1-41a7-a788-74e69f3fd0fb
Info 10:29:40: Finished disposing HostJupyterExecution  6941b51f-20c1-41a7-a788-74e69f3fd0fb
Info 10:29:40: Cleaning up server cache 6941b51f-20c1-41a7-a788-74e69f3fd0fb
Info 10:29:40: Finished disposing HostJupyterExecution  6941b51f-20c1-41a7-a788-74e69f3fd0fb
